spring:
  profiles:
    active: dev
    include: swagger,security
  application:
    name: k12servo
  jpa:
    hibernate:
      ddlAuto: update
    show_sql: true

  jackson:
    timeZone: GMT+8
    dateFormat: yyyy-MM-dd HH:mm:ss
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
    deserialization:
      READ_DATE_TIMESTAMPS_AS_NANOSECONDS: false
server:
  contextPath: /
  error:
    whitelabel:
      enabled: false

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: INFO
    cn.k12soft.servo: DEBUG

application:
  appName: k12servo
  superUser:
      mobile: 13100000001
      username: fenghua.wang
      password: 123456!
      gender: MALE

  third:
    easymob:
      appKey:
      clientId:
      clientSecret:
    aliyun:
      region: cn-qingdao
      accessKeyId: LTAIQRGtTyufG1GX
      accessKeySecret: ZRlHX7dvhgFsDVdVuWzhqLOxplSSWy
      sms:
        endpoint: https://1276178519321483.mns.cn-hangzhou.aliyuncs.com/
        topicName: sms.topic-cn-hangzhou
        signName: 博顿教育
        smsMessageBody: sms
        templateCodes:
          INVITATION: SMS_82020041
          RESET_PASSWORD: SMS_82010043
      sts:
        arn: acs:ram::1276178519321483:role/oss-manager-kidService
        tokenDuration: 86400
        policy:
          applyForToken: "{\"Statement\": [{
                               \"Action\": \"sts:AssumeRole\",
                               \"Effect\": \"Allow\",
                               \"Principal\": {
                                 \"Service\": [\"oas.aliyuncs.com\"]
                               }
                             }],
                           \"Version\": \"1\"}"