application:
  security:
    jwt:
      secret: k12soft@1703
    accessRules:
      - matcher:
          antPatterns:
            - /
            - /swagger-ui**
            - /swagger-resources/**
            - /webjars/**
            - /v2/api-docs/**
            - /static/**
            - /iclock/**
            - /visit/management/web/**
            - /district/management/**
            - /wxLogin/web/**

            - /users/**
            - /tokens/**
            - /schools
            - /nianhui/**
            - /expense/**
        access: permitAll
      - matcher:
          antPatterns:
            - /**
        access: authenticated
      - matcher:
         antPatterns:
           - /management/**
        access: hasAnyRole('MANAGER','TEACHER')
