debug: false
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:13307/k12web?serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: K12soft_qwer1234!
    driver-class-name: com.mysql.cj.jdbc.Driver